application:
  security:
    jwt:
      secret-key: yAQwgqXnXZEf+mx8etHOgQ8HP3iMMULkKZyJko6XtK4DLuaVcgejWwGRUAgILyKrUpHCylDmBYrVDFQ63jIecQ==
      expiration: 86400000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/