version: "3.8"

services:
  shopre-product-service:
    image: kunal2142/shopre-product-service
    container_name: shopre-product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shopre-product-db:5432/shopre-product-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://shopre-service-discovery:8761/eureka
    depends_on:
      - shopre-product-db
      - shopre-service-discovery
    networks:
      - shopre-network

  shopre-product-db:
    image: postgres:16-alpine
    container_name: shopre-product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopre-product-db
    ports:
      - "5440:5432"
    volumes:
      - shopre-product-db-data:/var/lib/postgresql/data
    networks:
      - shopre-network


  shopre-user-authentication-service:
    image: kunal2142/shopre-user-authentication-service
    container_name: shopre-user-authentication-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shopre-users-db:5432/shopre-users-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://shopre-service-discovery:8761/eureka
    depends_on:
      - shopre-users-db
      - shopre-service-discovery
    networks:
      - shopre-network

  shopre-users-db:
    image: postgres:16-alpine
    container_name: shopre-users-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopre-users-db
    ports:
      - "5441:5432"
    volumes:
      - shopre-users-db-data:/var/lib/postgresql/data
    networks:
      - shopre-network


  shopre-service-discovery:
    image: kunal2142/service-discovery
    container_name: shopre-service-discovery
    ports:
      - "8761:8761"
    networks:
      - shopre-network


  shopre-order-cart-service:
    image: kunal2142/shopre-order-and-cart-management-service
    container_name: shopre-order-cart-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://shopre-cart-db:5432/shopre-cart-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://shopre-service-discovery:8761/eureka
    depends_on:
      - shopre-cart-db
      - shopre-service-discovery
      - shopre-product-service
    networks:
      - shopre-network

  shopre-cart-db:
    image: postgres:16-alpine
    container_name: shopre-cart-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopre-cart-db
    ports:
      - "5442:5432"
    volumes:
      - shopre-cart-db-data:/var/lib/postgresql/data
    networks:
      - shopre-network



  shopre-api-gateway:
    image: kunal2142/shopre-api-gateway
    container_name: shopre-api-gateway
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://shopre-service-discovery:8761/eureka
    depends_on:
      - shopre-service-discovery
      - shopre-product-service
      - shopre-user-authentication-service
      - shopre-order-cart-service
    networks:
      - shopre-network


volumes:
  shopre-product-db-data:
  shopre-users-db-data:
  shopre-cart-db-data:

networks:
  shopre-network:
    driver: bridge